language: cpp

sudo: required

osx_image: xcode7.2

dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      compiler: gcc

git:
  submodules: false

before_install:
- git submodule update --init --recursive
- ./.travis.before_install.$TRAVIS_OS_NAME.sh

script:
- cd Dependencies
- ../premake.sh gmake
- make -j4
- cd ..
- ./premake.sh gmake
- make -j4

notifications:
  slack:
    rooms:
      secure: nn6rH9yj4/eJYNkAXrMIk4oVrweT3rznA5ATtuHzFeeG5uMT0qr1c1yQqDsSKsxtPan1RFo2awJ/PZkGQmuRVTcmVuaHs0eLPVrTXgfy2yjjuqwg4aLlK7PBEnv6oxUDyJOo9K9RYMcPIqXu0vcikgo+C4Oc6qL5MiOa7RleVjI=
    on_start: never
    on_success: always
    on_failure: always
